### ISSUE TITLE
investigate reducing debug binary size to decrease link time

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/rust-ipfs#107]

**Comment by koivunej** [comment]
Related: https://github.com/ipfs-rust/rust-ipfs/issues/63#issuecomment-602176158

**Comment by aphelionz** [comment]
@koivunej I believe you've done some work toward this. Not sure of its state but putting it in Phase 1.2 for now.

**Comment by koivunej** [comment]
I've been testing without any luck the combination of debug or release builds with different lto settings. Sadly even the release builds are slower..

I don't think this is in the grant scope. Quite essential to have though. I've been mostly doing the `ipfs-http` development in a throwaway binary crates which allow for near-interactive feedback from rls.

**Comment by aphelionz** [comment]
I'm wondering if we should make a bucket project for Phase 2+ items 🤔

**Comment by dvc94ch** [comment]
this should be a priority as it hinders productivity. the issue is not that checking the code is slow as @koivunej noted, but that it takes 20-30min to compile!

**Comment by aphelionz** [comment]
Some ideas to explore here:
- Selectively including `libp2p-*` subcrates
- Changing to `lld` linker
- Removing generic parameters from `Ipfs`

Add to the list too as you come up with other approaches

**Comment by aphelionz** [comment]
I agree, this should be a Phase 2.0 priority as it negatively impacts the developer experience.

**Comment by koivunej** [comment]
On cleaned workspace (`cargo clean`, but already downloaded deps) the `cargo check --workspace --tests` takes **2m 21s**. Touching `tests/pubsub.rs` and `cargo check --workspace --tests` takes **3.30s**.

Cleaned and only checked `cargo build --workspace --tests` takes **3m 25s**. Touching `tests/pubsub.rs` and `cargo build --workspace --tests` takes **37.21s** (links all binaries, probably not the examples).

I don't think this is terrible but I guess it's not good.

Creating a new binary crate with `cid` and `multibase` ~ **16s** to download and cargo build. Adding `libp2p` becomes **1m 19s**. Building a binary crate with `cid` + `multibase` + `multihash` is like **10s** after downloading deps.

Tried to box the filters at `http/src/v0.rs` but that is not possible to do at the level of this file, it might be possible at the functions returning the filters. That might speed things up.

@dvc94ch what takes 20-30min to compile for you?

**Comment by koivunej** [comment]
`RUSTFLAGS="-C linker=clang" cargo build --workspace --tests` on clean workspace **3m 10s**. Touching the `tests/pubsub.rs` and rebuilding: **26.80s**. The difference is likely inside the error margin as I didn't repeat these at all. 

After installing lld (`sudo apt install -y lld` on ubuntu 19.10 derivative installed `lld-9`) and with `RUSTFLAGS="-C link-arg=-fuse-ld=lld" cargo build --workspace --tests`:

 * after clean: **3m 01s**
 * after touching `tests/pubsub.rs`: **19.10s**

Maybe I'll start using this lld-9 then with the `.cargo/config` tip from https://github.com/rust-lang/rust/issues/39915#issuecomment-538049306. Could be that the installation of `lld` or `lld-9` now allows `-C linker=clang` to use it right away:

* after clean: **3m 19s**
* after touching `tests/pubsub.rs`: **26.43s**

All my measurements have heavy variance because of using firefox at the same time.

**Comment by aphelionz** [comment]
Late 2012 Mac Mini on current master branch

```bash
$ rm -rf /target
$ time cargo build --workspace
```

- 1402.83s user
- 118.26s system
- 144% cpu 
- **17:31.86 total**

**Comment by koivunej** [comment]
@aphelionz was that with or without lld-9?

Could you put my wip `refs` to compile when you can, with the same configuration? I'd expect some +5 minutes or more.

**Comment by aphelionz** [comment]
Well test today.

> I'd expect some +5 minutes or more.

Not good, if true. There's still lots more work to do and if the builds times keep increasing it's definitely going to slow down even more.

**Comment by koivunej** [comment]
Looked into making `blake2{b,s}_simd` features in multihash and libipld-base, libipld with no changes. This was following the `cargo bloat` guesses.

Looked into profiling the build [following this](https://blog.rust-lang.org/inside-rust/2020/02/25/intro-rustc-self-profile.html) with `RUSTFLAGS=-Zself-profile` ... Linker time is likely less than suspected, of the 169s for the ipfs-http binary most time was spent on `codegen_fulfill_obligation`, `normalize_projection_ty`, `LLVM_passes` and `evaluate_obligation` then `codegen_crate`. Sadly we cannot use `crox` as the json file grows to 4GB with any additional information. Didn't get anything useful from llvm_timings.json.

Perhaps the next thing to try in `ipfs-http` is to make the routes boxed.

**Comment by koivunej** [comment]
Investigated boxing the routes and it looks good in #163, less than half a minute incremental builds.

**Comment by aphelionz** [comment]
Tested this locally.

Before: 4m 47s
With #163 :  2m 14s

After an edit, 6.55 seconds.

I'm comfortable closing this ticket.
