### ISSUE TITLE
Management of interests of different groups involved in rust-ipfs

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/rust-ipfs#129]
So I feel there is a problem of differing interests that need to be accomodated. I'm not really sure what the best way to do this is. For the time being I demoted all owners to members until this is figured out, as I believe that open source is about collaboration, which is only possible if all interests are adequately represented.

I also added @4meta5 to the organization as a member, he'll be approving my pr's, as currently there are only two active contributors that are both working for the same company. It's ok for you to continue approving each others PR's.

Best,
David Craven

**Comment by aphelionz** [comment]
Welcome @4meta5, it's good to have you in the org. Personally speaking I want to work through these issues and I believe we are making progress towards that end. I agree that open source should be about collaboration and that this is possible here.

**Comment by dvc94ch** [comment]
Closing this issue for now, immediate challanges have been or are being resolved
