### ISSUE TITLE
Privacy / Encryption

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#138]
In this issue a tangential discussion was started with regards to limiting access to data or protecting certain data. Some ideas were:
- Private networks
- Encrypted stores
- Access Control (not specified)

Agreement was reached to open a new issue to discuss this, so here it is!

**Comment by koivunej** [comment]
I wonder if this should be on https://github.com/ipfs/notes instead? There is at least a label called [Candidate Open Problem](https://github.com/ipfs/notes/issues?q=is%3Aissue+is%3Aopen+encryption+label%3A%22Candidate+Open+Problem%22) which at least seems to cover the topics on the issue description, and more.

**Comment by aphelionz** [comment]
Yes, agreed. More or less covered in detail in https://github.com/ipfs/notes/issues/270 and other issues in the aforementioned label. 

Closing for now and folks can re-open if they want to talk about encryption _in the context of Rust IPFS_.

**Comment by dvc94ch** [comment]
I'm tending towards encryption is out of scope for rust-ipfs and privacy issues are for libp2p to deal with.

**Comment by dvc94ch** [comment]
Also note that there is a theorem somewhere that there is a triangle (privacy, latency, bandwidth) and any solution needs to be within that triangle, so there are no magic solutions. I can dig it up if someone is interested.

**Comment by alexjg** [comment]
Definitely there are a lot of tradeoffs, I guess for me (as an observer who isn't contributing anything at all right now) the ideal world would be one where `rust-ipfs` isn't opinionated about which tradeoffs I make as an application developer.

**Comment by dvc94ch** [comment]
That's what I want too. The http api's are too opinionated and limiting. If you use libp2p you can choose which protocols you want to use and add your own. That's not possible with the http api as it includes the kitchen sink.
