### ISSUE TITLE
yamux transport is broken for rust-ipfs to go-ipfs communication

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/rust-ipfs#24]

**Comment by koivunej** [comment]
I wonder if this is still an issue? I guess this could be tested by turning the order od muxer configurations around, so that yamux would be preferred. I should add instructions how to run the example(s) against go-ipfs.

**Comment by dvc94ch** [comment]
don't know if it's still an issue, might have resolved itself

**Comment by rklaehn** [comment]
Do we have a reproducer for this? For the things I have been trying, yamux works just fine.

**Comment by koivunej** [comment]
Yeah it has most likely advanced a lot. I probably asked about this while fighting the typeck with swarm so this could most likely just be closed.
