### ISSUE TITLE
rustfmt run and travis integration

### ISSUE THREAD

**Issue by koivunej** [ipfs-rust/rust-ipfs#42]
Similar to how clippy was added, rustfmt could be integrated. I think the codebase is already quite rustfmt-ish so there shouldn't be huge changes.

Adding good first issue as there shouldn't be any issues here. Travis might not install the `rustfmt` component by default as it did not install `clippy` either. Before making the formatting changes make sure the `cargo fmt -- --check` or whatever CI command fails as there currently should be some formatting issues.

**Comment by aphelionz** [comment]
This appears to be done, yeah? Can we close?
