### ISSUE TITLE
Processes with the grant work

### ISSUE THREAD

**Issue by koivunej** [ipfs-rust/rust-ipfs#56]
I propose we aim to work by issues which define the goals when starting and going uphill and be refined during discovery. Larger goals are tackled with "tracking issues" which simply link to multiple issues similar to #59 which links this issue.

For example: phase 1.0 will be a “tracking issue” with links to other issues regarding specific work we know we need to accomplish. We might find that we’d like to split tasks under the “tracking issues” and that should be done as needed. Assignment should help us not duplicate work. Code will be presented for review using pull-requests as have been so far. During the completion of a phase we can finally close the phase 1.0 issue as hopefully all of it’s subtasks have been completed.

**Comment by koivunej** [comment]
Using the first comment here to note @aphelionz proposal of using organization wide projects, as in https://github.com/orgs/ipfs-rust/projects and the related board style ui.

I have no experience with working with the github projects and boards and lean towards rust-lang style tracking issues for everything, but those would be fine with me. At least building a tracking issue wasn't easy as I had hoped, and I probably missed some github tricks so going with the projects would allow me not having to learn about those tricks :)

**Comment by aphelionz** [comment]
Thanks @koivunej. I want to stress here your excellent choice of words. My making those projects is indeed a _proposal_ and I imagine the collaboration process will in and of itself change.

Thinking about it more: Without too many moving parts, everybody should be enabled to be as agnostic as possible when it comes to HOW they VIEW the data contained in the issues. Some people may prefer a tracking issue with check boxes in it, some people might appreciate a kanban board, still others want milestones. I'd love to hear from more folks with regards to this.

**Comment by koivunej** [comment]
Now that we've had the both in use, and I created tracking issue which I did for these roadmap-y items, perhaps the projects are more ergonomic and easier to get right here, also the #65 needs double the amount of updates (ticking the boxes).. So maybe let's try projects-only for phase 1.1 and maybe reconsider when we learn more? :)

**Comment by aphelionz** [comment]
Fine with me!

**Comment by aphelionz** [comment]
Closing this for now, we can re-open if need be.
