### ISSUE TITLE
HTTP v0 API for testing

### ISSUE THREAD

**Issue by koivunej** [ipfs-rust/rust-ipfs#60]
Per the grant plan testing with [`interface-js-ipfs-core`](https://github.com/ipfs/interface-js-ipfs-core/) and [`interop`](https://github.com/ipfs/interop/) requires an [HTTP v0 API](https://docs-beta.ipfs.io/reference/http/api/). The launch an ipfs "daemon" part of the two test resources is in [`js-ipfsd-ctl`](https://github.com/ipfs/js-ipfsd-ctl).

I understand the "daemon" to be just a process like go-ipfs `daemon` which will hang in the foreground until `POST /shutdown` has been initiated, but this should be verified with the tests of `js-ipfsd-ctl`.

The API endpoints we need in phase 1.0 can all return "501 Not Implemented" except for `/shutdown` which should allow us to stop the process gracefully. The test cases of js-ipfsd-ctl expect `/id` to return something.

Command line option `init` should do similar directory setup and keygen as `go-ipfs init` at the `IPFS_PATH` set by the environment. During normal startup there can be other arguments but after listening has been started, api listening address needs to be print `API listening on: $multiaddr` and finally a `daemon is running` line must be output.

`init` should produce an empty file called "api" inside the `IPFS_PATH`, which should be written to when the listening has started with the `$multiaddr` and on exit the file should be truncated.

In channel discussions a `rust-ipfs/{http,cli}` was suggested and adding such to the root `Cargo.toml` workspace and a relative dependency seems to work.

**Comment by koivunej** [comment]
As mentioned in the chat I'll be prototyping on this and hopefully finding more about the js-ipfsd-ctl's requirements tomorrow.

**Comment by aphelionz** [comment]
> The test cases of js-ipfsd-ctl expect /id

Would that mean that we only really need two endpoints for Phase 1.0, `/id` and `/shutdown` since having `/id` return `501 NOT IMPLEMENTED` would effectively tank every test anyway?

**Comment by aphelionz** [comment]
> init should produce an empty file called "api" inside the IPFS_PATH
And also create the IPFS_PATH folder if it doesn't exist yet, correct? cc @vmx

**Comment by aphelionz** [comment]
> Cargo.toml workspace

The current project is not a workspace project so we should probably transition to a Cargo workspace in a separate PR.

**Comment by koivunej** [comment]
> Would that mean that we only really need two endpoints for Phase 1.0, /id and /shutdown since having /id return 501 NOT IMPLEMENTED would effectively tank every test anyway?

What I remember reading yesterday was that the spawn operation and/or tests fail without the things I mentioned in the description. Without a working spawn, I guess we should be getting failing tests but I'd like to see at minimum some of the real requests hitting the http server.

> > init should produce an empty file called "api" inside the IPFS_PATH
> 
> And also create the IPFS_PATH folder if it doesn't exist yet, correct? ...

I think there was an ability to create indisposable daemons (as in, not for testing) and this might vary a bit. In general I remember `ipfs init` creating the `IPFS_PATH` but I'd expect the test cases to  tell us.

**Comment by vmx** [comment]
@hugomrdias is maintaining ipfsd-ctl so he should be able to answer all those questions.

**Comment by koivunej** [comment]
Looked at this today and pushed some WIP, had some issues understanding the inner workings of `js-ipfsd-ctl`:

 * https://github.com/eqlabs/rust-ipfs/tree/http_v0_for_testing contains the work in progress code
 * https://github.com/koivunej/js-ipfsd-ctl/tree/add_rust_ipfs_http passes `test/factory.spec.js`

Mark will probably pick up from here as we operate in different timezones but if you happen to stumble upon the code, please understand I've tried to do the minimum amount of work to understand more of the expectations of the libraries and to get us to failing test results as fast as possible. This includes copy pasting the output of `api/v0/id` :)

To repeat the test successes:

 1. checkout my fork of `rust-ipfs`, run `cargo build` under `rust-ipfs/http`
 2. make sure you can execute `rust-ipfs/target/debug/http` (it autogenerated help presented by default)
 3. set env variable `IPFS_RUST_EXEC` to the executable tested in step 2
 4. `npm run test:node` should now have passing tests for the branch of `js-ipfsd-ctl`

The convention of `IPFS_type_EXEC` is mentioned in the README but no longer greppable from the `js-ipfsd-ctl` but this will probably do until we get something packaged similar to `go-ipfs-dep`. When debugging the tests I found it useful to wrap the `IPFS_RUST_EXEC` in a bash script which will use `tee -a` to append everything to a log file, but at least this method leaves `http` processes running.
