### ISSUE TITLE
Repo Health Checks 

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#62]
CI in place? Testing? Linting? Clippy? etc etc.

This can be done manually for now but we'll likely need to automate this as we start adding more

**Comment by dvc94ch** [comment]
I think this is in place. @aphelionz do you think there is something missing?

**Comment by aphelionz** [comment]
Yes, I think were great for now, though I think I'd like to wait until the branches with CI enabled are merged into `rust-ipld` before closing this issue.

Should any other repos be covered by these standards besides `rust-ipfs` and `rust-ipld`?

**Comment by dvc94ch** [comment]
`ipld-collections` maybe, but for the time being it's not covered by the grant. I might continue work on the ipld-daemon later, but for now it's abandoned.
