### ISSUE TITLE
Dependency Analysis

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#63]
Based on #59 , I'd like to perform a pretty in-depth traversal of the dependency chain to see if anything stands out, at the very least.

**Comment by aphelionz** [comment]
Ran the following from inside the `rust-ipfs` folder

```bash
$ cargo install cargo-deps
$ cargo deps -d 3 --no-transitive-deps --subgraph libp2p* -o rust-ipfs.dot
$ dot -Tpng > rainbow-graph.png rust-ipfs.dot
```

Playing with the cargo deps options for a bit yielded something I can parse:

![image](https://user-images.githubusercontent.com/106148/76010413-d526da80-5ee0-11ea-84be-b661279dbe2e.png)

It looks like our primary dependency, `libp2p` uses `async-std` and then 3 layers down the only mention of `tokio` comes from the `domain` dependency.

**Comment by koivunej** [comment]
Try that for the http crate and you'll find at least two tokios and bunch of more crates.

Yes, the version we currently have of libp2p uses async-std and the latest changes remove the direct use of tokio. I'm more curious of the two multibases, but that'd probably go away when upgrading the dependencies.

**Comment by aphelionz** [comment]
Right, good call with the multibases. Regardless of whether this helps us choose a runtime I still think this type of analysis is useful

**Comment by aphelionz** [comment]
> Try that for the http crate

![image](https://user-images.githubusercontent.com/106148/76017057-f0e3ae00-5eeb-11ea-8d1f-83c84eb3c34d.png)

**Comment by koivunej** [comment]
While tangentially related, I think I checked few days ago the sizes of `--release` binaries:

 * 12MB for examples/ipfs-bitswap-test (now under examples/examples/ipfs-bitswap-test)
 * 14MB for ipfs-http

The first is to estimate the size of "ipfs" and the second is to see how much overhead bringing tokio, warp, hyper and all gives.

Esp. the ipfs-http debug binary is huge (220MB). By the looks of [`cargo-bloat`](https://github.com/RazrFalcon/cargo-bloat) the top 20-ish something is different versions of hash algorithms, which I assume the linker throws mostly away during release builds.

I think this issue could be closed as we are already tracking unrelesed versions in #75.

**Comment by dvc94ch** [comment]
Making debug builds smaller would decrease compile times, as they are way to high currently.
