### ISSUE TITLE
Support for /version endpoint

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#78]
This should just return a static string for the version. Bonus points if we can update this automatically when Cargo.toml is modified and/or when we do a new release

**Comment by koivunej** [comment]
Ref docs: https://docs-beta.ipfs.io/reference/http/api/#api-v0-version and js-ipfs impl: https://github.com/ipfs/js-ipfs/blob/master/packages/ipfs/src/http/api/resources/version.js. These seem to differ on the `Golang` and `System` attributes, likely no test is using those.

I might as well do this before looking into making the ipfs value usable in `/id`.

The proper way might be to embedded or offer the commit and version information on the rust-ipfs crate itself, so these would never be in conflict. Looks like [`vergen`](https://docs.rs/vergen/3.0.4/vergen/) would be the way to go, while quite heavy. Lets try it out in http before moving to `rust-ipfs`. Could be that crate users would prefer to use their own version always as that'd lead to the actual used `rust-ipfs` version.

**Comment by koivunej** [comment]
in `go-ipfs` 0.4.23 in addition to `/api/v0/version` there is a plaintext returning `/version` which does not handle arguments. Also it'd seem that the args do get parsed but not used to control the output (cli probably does that).
