### ISSUE TITLE
Add web API

### ISSUE THREAD

**Issue by dvc94ch** [ipfs-rust/rust-ipfs#9]
We don't have to reimplement a cli since https://github.com/ferristseng/rust-ipfs-api looks nice.

**Comment by adamski** [comment]
Are you suggesting using that library to talk to a local node instead of a remote one?

**Comment by dvc94ch** [comment]
It's how the go and js cli interfaces an IPFS work. You start the daemon and communicate through the http api. The cli talking to the api is already implemented, we just need to implement the other end.

**Comment by adamski** [comment]
Ok, sounds good.

**Comment by adamski** [comment]
Ok, so probably using https://hyper.rs? I see that is also used in `rust-ipfs-api`

**Comment by adamski** [comment]
For reference, this looks like the spec that needs implementing: https://ipfs.docs.apiary.io

**Comment by gnunicorn** [comment]
> Ok, so probably using https://hyper.rs? I see that is also used in `rust-ipfs-api`

Or `actix-web`. They also have `actix-web`-support. I personally would prefer us using `actix-web`-server-side, too.

**Comment by dvc94ch** [comment]
Or `tower-rs`. But I don't have a strong opinion.

**Comment by koivunej** [comment]
`warp` seems like a good choice for this but may lag behind any tokio 0.2 or std::futures migration. There seems to have been already a gateway server attempt in https://github.com/dvc94ch/rust-ipfs/pull/28 ... I wonder why that one was closed? I understand gateway was probably different from a an http api but the question still stands.

**Comment by aphelionz** [comment]
Work has begin on this using warp and this ticket might now be duplicated by #60 . Should we close this one for now?
