### ISSUE TITLE
Support for /refs endpoints

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#92]
References:
* https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/refs.js
* https://docs-beta.ipfs.io/reference/http/api/#api-v0-refs
* https://github.com/ipfs/interop (no occurrences) 

### /refs
List links (references) from an object.
`curl "http://localhost:5001/api/v0/refs?arg=<ipfs-path>&format=<dst>&edges=<value>&unique=<value>&recursive=<value>&max-depth=-1"`

- Requires `object.put` Need to refactor tests.
- Arguments
    - arg [string]: Path to the object(s) to list refs from. Required: yes.
    - format [string]: Emit edges with given format. Available tokens: <src> <dst> <linkname>. Default: <dst>. Default: "<dst>". Required: no.
    - edges [bool]: Emit edge format: <from> -> <to>. Required: no.
    - unique [bool]: Omit duplicate refs from output. Required: no.
    - recursive [bool]: Recursively list links of child nodes. Required: no.
    - max-depth [int]: Only for recursive refs, limits fetch and listing to the given depth. Default: "-1". Required: no.
- On success, the call to this endpoint will return with 200 and the following body:

```
{
  "Err": "<string>",
  "Ref": "<string>"
}
```

### /refs/local
List all local references.
`curl "http://localhost:5001/api/v0/refs/local"`

- Test requires IPFS add, perhaps we can refactor to `ipfs.dag.put`
- This endpoint takes no arguments.
- On success, the call to this endpoint will return with 200 and the following body:
```
{
  "Err": "<string>",
  "Ref": "<string>"
}
```

**Comment by aphelionz** [comment]
@vmx and @hugomrdias Looks like these interface tests use the `object` api. Should we plan to refactor those to `/block`?

**Comment by hugomrdias** [comment]
yes

**Comment by aphelionz** [comment]
@hugomrdias @vmx Forgive the potentially very basic question, but what is the transliteration between `ipfs.add` and `ipfs.block.put`, and also `ipfs.object.put` and `ipfs.block.put`? Default options are OK. I have the tests refactored and working but I'm 99.999999% sure I didn't do it correctly. For example in the [refs.local](https://github.com/ipfs/js-ipfs/blob/master/packages/interface-ipfs-core/src/refs-local.js) tests:

```diff
- await all(ipfs.add(dirs))
+ await all(dirs.map(dir => ipfs.block.put(dir.content)))
```

**Comment by vmx** [comment]
> but what is the transliteration between `ipfs.add` and `ipfs.block.put`

They do different things:

 - `ipfs.add()` adds files, which includes chunking, which leads to several blocks. 
 - `ipld.block`put()` adds a single already encoded block.


> `ipfs.object.put` and `ipfs.block.put`

You could think of `ipfs.object.put()` as adding a not yet encoded DagPB node. `ipfs.block.put()` puts an already encoded block. So if you want to use `ipfs.block.put()` instead of `ipfs.object.put()`, you would take the input `ipfs.object.put()` takes, encode it with IPLD and use that encoded block as parameter for `ipfs.block.put()`.

**Comment by aphelionz** [comment]
In terms of `ipfs.add`, would it be acceptable them to change the hashes in the tests so that they match the output?

**Comment by vmx** [comment]
Without having a closer look, I'd expect that `ipfs.add()` calls could be replaces with simpler `ipfs.block.put()` calls while still testing the same thing.

**Comment by aphelionz** [comment]
Ok, I'll be making a PR to that effect then :+1:

**Comment by aphelionz** [comment]
A number of PRs were made to js-ipfs
* https://github.com/ipfs/js-ipfs/pull/2980
* https://github.com/ipfs/js-ipfs/pull/2983
* https://github.com/ipfs/js-ipfs/pull/2972
* https://github.com/ipfs/js-ipfs/pull/2982
