### ISSUE TITLE
Support for /bitswap endpoints

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/rust-ipfs#93]
Finish work to wire up the `/bitswap/*` endpoints

**Comment by koivunej** [comment]
#131 has passes the conformance tests for `/bitswap/{stat,wantlist}`, there's also a passing block exchange integration test between two `rust-ipfs` nodes but I there are no checks for the accounting side of things.

**Comment by koivunej** [comment]
`/bitswap/stat` or `bitswap::Bitswap` doesn't add the sent data at the moment at all, nor does it handle disconnecting peers in any way (it could for example merge the stats from removed ledgers into some more long lived counters, and keep starting the ledgers from zero).

**Comment by aphelionz** [comment]
@koivunej can this be closed?

**Comment by koivunej** [comment]
Yeah, the endpoints are there even if bitswap needs more care. Probably we need to add assertions for the counts before and more tests overall before enhancing. I tried to prototype a new interop test yesterday for just exchanging blocks between js, go and rust-ipfs but.. I would love to write it in rust but my javascript skills are a bit lacking. When testing the related PRs, I am 95% sure the block exchange worked with go-ipfs 0.4.23.
